global:
  scrape_interval: 5s

scrape_configs:
  # scrape API directly (inside the compose network)
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  # optional: scrape via Nginx over HTTPS (mkcert in dev)
  - job_name: "edge-nginx"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["nginx:443"]
    tls_config:
      insecure_skip_verify: true   # mkcert/self-signed in dev only
